### ISSUE TITLE
Integración de proveedores MID con el microcliente de gestión contractual.

### ISSUE THREAD

**Issue by edwargl7** [udistrital/argo_documentacion#80]
Se requiere realizar la integración del microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid) con el microcliente de [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) en el paso de información del contratista basado en el [Mockup](https://github.com/user-attachments/assets/80f88335-7ac8-48ac-ba78-8164175de2ac).

**Sub Tareas**

- [ ] Ajuste en los campos visualizados de información del contratista basado en la imagen del Mockup (se remueven unos campos de información del contratista como información bancaria y se agrega información del representante legal).
- [x] Implementación de la integración con el microservicio de proveedores endpoint de consulta de proveedores (sin traer información del representante legal - caso persona jurídica).
- [x] Implementación de la integración con el microservicio de proveedores endpoint de consulta de representante legal por id del proveedor (persona jurídica).
- [ ] Pruebas funcionales de la consulta de un proveedor (persona natural).
- [ ] Pruebas funcionales de la consulta de un proveedor (persona jurídica).

**Escenarios de pruebas**
- [ ] Consulta exitosa de un proveedor persona natural. Con la correcta visualización de los datos (sin visualizar los campos de representante legal).
- [ ] Consulta exitosa de un proveedor persona jurídica. Con la correcta visualización de los datos (visualizando los campos de representante legal).

**Criterios de aceptación**

- [ ] Documentación de las pruebas realizadas con la integración del endpoint de consulta de proveedor.

**Requerimientos**

- Completar la Issue #74 

**Material de apoyo**
- Imagen Mockup paso de información del contratista.
![image](https://github.com/user-attachments/assets/80f88335-7ac8-48ac-ba78-8164175de2ac)

**Especificaciones técnicas**
1. Repositorio de microservicio [proveedores_mid](https://github.com/udistrital/proveedores_mid).
2. Repositorio de microcliente [gestion_contractual_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se debe visualizar para persona natural de la siguiente manera
![image](https://github.com/user-attachments/assets/c8409a40-5e7c-4b7c-991f-4d40be06af91)

Y persona Jurídica:
![image](https://github.com/user-attachments/assets/b5e2502d-af08-40f5-8a7e-f041ca5a2f8c)

**Comment by mau-oati** [comment]
**ToDo:** Visualizar correctamente el objeto en cada tipo de response, validar y pruebas.

**Comment by edwargl7** [comment]
Realiza un ajuste importante en el manejo de errores.
![image](https://github.com/user-attachments/assets/b7bbecdd-f067-48f6-9a82-5366f4f48fa1)

Se continuará el siguiente sprint con esta Issue.
Para el manejo del input de búsqueda revisar la siguiente línea.
```html
<input matInput formControlName="documentoContratista" (keyup.enter)="buscarContratista()" placeholder="Escribe y presiona Enter">
```

**Comment by edwargl7** [comment]
En la Issue #92 se completará la integración con el microservicio de proveedores mid.
